title: MyBlog
description: プログラミングの学習記録
author: nakata
theme: minima

# GitHub Pages settings
url: "https://kei-600th.github.io"
baseurl: "/myblog"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include assets directory
include:
  - assets

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/
